name: Testing independent jobs

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hellow World'
  job-2: 
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - run: babdajsb
  job-3: 
    runs-on: ubuntu-latest
    needs:
      - job-1
      - job-2
    if: ${{ always() }}
    steps:
      - run: echo 'one more time'

    
